### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method newTexture on channel opengl_texture)

### ISSUE THREAD

**Issue by zinwalin** [luoyibu/flutter_texture#1]
`[ +265 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.texture_image/.MainActivity (has extras) }
[   +2 ms] Application running.
[   +1 ms] To quit, press "q".
[+1021 ms] E/flutter (26119): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method newTexture on channel opengl_texture)
[        ] E/flutter (26119): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
[        ] E/flutter (26119): <asynchronous suspension>
[        ] E/flutter (26119): #1      _MyHomePageState.newTexture (package:texture_image/main.dart:53)
[        ] E/flutter (26119): #2      _MyHomePageState.initState (package:texture_image/main.dart:49)
[        ] E/flutter (26119): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355)
[        ] E/flutter (26119): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
[        ] E/flutter (26119): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
[        ] E/flutter (26119): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
[        ] E/flutter (26119): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
[        ] E/flutter (26119): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
[        ] E/flutter (26119): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
[        ] E/flutter (26119): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
[        ] E/flutter (26119): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
[        ] E/flutter (26119): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
[        ] E/flutter (26119): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
[        ] E/flutter (26119): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
[        ] E/flutter (26119): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
[        ] E/flutter (26119): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
[        ] E/flutter (26119): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
[        ] E/flutter (26119): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
[        ] E/flutter (26119): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
[        ] E/flutter (26119): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
[        ] E/flutter (26119): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
[        ] E/flutter (26119): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
[        ] E/flutter (26119): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
[        ] E/flutter (26119): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
[        ] E/flutter (26119): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
[        ] E/flutter (26119): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
[        ] E/flutter (26119): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
[        ] E/flutter (26119): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
[        ] E/flutter (26119): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
[        ] E/flutter (26119): #46     Element.inflateWidget (package:flutter/src/widgets/framework.
`

**Comment by luoyibu** [comment]
目前只支持iOS真机运行，安卓这边不太熟
